name: dev test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      working-directory: ./cicd_pipeline_test
      CI: false
    runs-on: ubuntu-latest

    #    strategy:
    #      matrix:
    #        node-version: [18.x, 20.x]
    steps:
      #      - uses: actions/checkout@v3
      #      - name: Use Node.js ${{ matrix.node-version }}
      #        uses: actions/setup-node@v3
      #        with:
      #          node-version: ${{ matrix.node-version }}

      - name: SSH ACTION!
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/srms2_dev/serving-robot-management-system-frontend/
            ls -al
            sudo git pull origin develop
            #ls -al ~/hprobot-build/srms-test/build
