# Base image with Node.js for development
FROM node:14 AS base

WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Development stage to enable live-reloading
FROM base AS development

# EXPOSE 8080

CMD ["npm", "run", "dev"]
