# Step 1: Build the Vue.js application
FROM node:14 AS build

WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package*.json ./
RUN npm install

# Copy the rest of the application code and build
COPY . .
RUN npm run build

# Step 2: Serve the production build using a lightweight HTTP server
FROM nginx:alpine

# Remove the default Nginx configurations
RUN rm -rf /etc/nginx/conf.d

# Copy the Nginx configuration for the Vue.js app
COPY nginx /etc/nginx/

# Copy the production build from the build stage
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
