name: dev test

on:
  push:
    branches: [develop]
jobs:
  build:
    env:
      working-directory: ./cicd_pipeline_test
      CI: false
    runs-on: ubuntu-latest

    #    strategy:
    #      matrix:
    #        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      #      - name: Use Node.js ${{ matrix.node-version }}
      #        uses: actions/setup-node@v3
      #        with:
      #          node-version: ${{ matrix.node-version }}
      - name: Docker Hub build & push
        run: |
          ls -al
          cd cicd_pipeline_test
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} -f Dockerfile.dev .
          docker images
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

      - name: SSH ACTION!
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # cd ~/CICD_pipeline_demo/
            # ls -al
            # sudo git pull origin develop
            # cd cicd_pipeline_test/

            # #ls -al ~/hprobot-build/srms-test/build

            cd /home/ubuntu/CICD_pipeline_demo/cicd_pipeline_test/
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
            sudo docker rm -f test-app-dev
            sudo docker run -d -p 3003:5173 --name test-app-dev ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
            # sudo docker-compose up -d
            sudo docker image prune -f
